### ISSUE TITLE
Error clicking app menu

### ISSUE THREAD

**Issue by OpencloudPro** [OCA/dms#101]
Traceabilidade:
TypeError: values.forEach is not a function
    at SearchPanelModelExtension._createFilterTree (https://obm.opencloud.pro/web/content/378-ba8a7de/web.assets_backend.js:2030:8)
    at https://obm.opencloud.pro/web/content/378-ba8a7de/web.assets_backend.js:2041:581
    at async Promise.all (index 0)
    at async SearchPanelModelExtension._fetchFilters (https://obm.opencloud.pro/web/content/378-ba8a7de/web.assets_backend.js:2041:48)
    at async SearchPanelModelExtension._fetchSections (https://obm.opencloud.pro/web/content/378-ba8a7de/web.assets_backend.js:2042:118)
    at async SearchPanelModelExtension.load (https://obm.opencloud.pro/web/content/378-ba8a7de/web.assets_backend.js:2013:119)
    at async SearchPanelModelExtension.callLoad (https://obm.opencloud.pro/web/content/378-ba8a7de/web.assets_backend.js:1301:66)
    at async SearchPanelModelExtension.callLoad (https://obm.opencloud.pro/web/content/378-ba8a7de/web.assets_backend.js:2086:564)
    at async SearchPanelModelExtension.callLoad (https://obm.opencloud.pro/web/content/378-ba8a7de/web.assets_backend.js:2007:62)
    at async Promise.all (index 0)

**Comment by pedrobaeza** [comment]
Is this reproducible on OCA runbot?

**Comment by OpencloudPro** [comment]
Hi @pedrobaeza , 
no, on our own server that has the latest Odoo v14 branch. 

Thanks.

**Comment by pedrobaeza** [comment]
Then if no reproducible or steps to get to it, nothing can be done.

**Comment by OpencloudPro** [comment]
Its resolved, was a bug from our side. 
Thanks.
