### ISSUE TITLE
[13.0] Error in portal when trying to access directory

### ISSUE THREAD

**Issue by santyabreu** [OCA/dms#130]
Hello, Im in the community version of odoo, v13

When trying to access to the directory section, after installing the module and configure it with a group:

![image](https://user-images.githubusercontent.com/40429279/129869193-1a93a706-6a2d-425e-bd30-1a6c54513504.png)

, the system gives me this extrange error:

![image](https://user-images.githubusercontent.com/40429279/129869451-6b619aec-d20e-4204-8e04-8784cf2a5f94.png)

This is the trace:

traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/opt/odoo/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.access', <function IrModelAccess.check at 0x7f967936bea0>, 8, False, 'account.move', 'read', True, ('es_ES',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/odoo/http.py", line 804, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/dms/controllers/portal.py", line 65, in portal_my_dms
    values = self._prepare_portal_layout_values()
  File "/opt/odoo/odoo/addons/dms/controllers/portal.py", line 33, in _prepare_portal_layout_values
    values = super()._prepare_portal_layout_values()
  File "/opt/odoo/odoo/addons/sale/controllers/portal.py", line 18, in _prepare_portal_layout_values
    values = super(CustomerPortal, self)._prepare_portal_layout_values()
  File "/opt/odoo/odoo/addons/hr_timesheet/controllers/portal.py", line 19, in _prepare_portal_layout_values
    values = super(TimesheetCustomerPortal, self)._prepare_portal_layout_values()
  File "/opt/odoo/odoo/addons/crnd_wsd/controllers/main.py", line 445, in _prepare_portal_layout_values
    RequestCustomerPortal, self)._prepare_portal_layout_values()
  File "/opt/odoo/odoo/addons/project/controllers/portal.py", line 19, in _prepare_portal_layout_values
    values = super(CustomerPortal, self)._prepare_portal_layout_values()
  File "/opt/odoo/odoo/addons/account/controllers/portal.py", line 15, in _prepare_portal_layout_values
    ('type', 'in', ('out_invoice', 'in_invoice', 'out_refund', 'in_refund', 'out_receipt', 'in_receipt')),
  File "/opt/odoo/odoo/odoo/models.py", line 1595, in search_count
    res = self.search(args, count=True)
  File "/opt/odoo/odoo/odoo/models.py", line 1618, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo/odoo/odoo/models.py", line 4373, in _search
    model.check_access_rights('read')
  File "/opt/odoo/odoo/odoo/models.py", line 3213, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-22>", line 2, in check
  File "/opt/odoo/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_model.py", line 1549, in check
    raise AccessError(msg % msg_params)
odoo.exceptions.AccessError: ("Lo sentimos, no tiene permiso para acceder a documentos de tipo 'Asientos contables' (account.move). Esta operación está permitida para los grupos:\n\t- Expenses/Team Approver\n\t- Expenses/Team Approver\n\t- Invoicing/Billing\n\t- Invoicing/Billing Administrator\n\t- Sales/Administrator\n\t- Sales/User: Own Documents Only\n\t- User types/Portal - (Operación: read, Usuario: 8)", None)

Can you help me with this

**Comment by santyabreu** [comment]
Resuelto, entraba en conflicto con los Attached documments.
