### ISSUE TITLE
[14.0] Create Directory | TypeError: 'NewId' object is not iterable

### ISSUE THREAD

**Issue by EricNLecuyer** [OCA/dms#137]
On a fresh install, I am able to create Storage and Files, but whenever I try to create a Directory (either from the Storage page or the "Create" button on the Directory page), I get the following error:

`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1359, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/models.py", line 6128, in onchange
    value = record[name]
  File "/opt/odoo/odoo/models.py", line 5617, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo/fields.py", line 973, in __get__
    self.compute_value(recs)
  File "/opt/odoo/odoo/fields.py", line 1112, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/opt/odoo/odoo/models.py", line 4020, in _compute_field_value
    getattr(self, field.compute)()
  File "/opt/odoo/addons/dms/models/directory.py", line 416, in _compute_count_total_directories
    count = self.search_count([("id", "child_of", record.id)])
  File "/opt/odoo/odoo/models.py", line 1674, in search_count
    res = self.search(args, count=True)
  File "/opt/odoo/odoo/models.py", line 1697, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo/odoo/models.py", line 4453, in _search
    query = self._where_calc(args)
  File "/opt/odoo/odoo/models.py", line 4209, in _where_calc
    return expression.expression(domain, self).query
  File "/opt/odoo/odoo/osv/expression.py", line 438, in __init__
    self.parse()
  File "/opt/odoo/odoo/osv/expression.py", line 651, in parse
    ids2 = to_ids(right, model, leaf)
  File "/opt/odoo/odoo/osv/expression.py", line 520, in to_ids
    return list(value)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: 'NewId' object is not iterable`

I tried removing demo data, restarting the server, going in and out of dev mode and adjusting permissions but the error remains. For reference, I am using the latest version of dms and Odoo 14.1 CE.

Could something be misconfigured on my side? Please let me know if you need more info.

Thank you for your help!

**Comment by pedrobaeza** [comment]
Please try to reproduce the problem in OCA runbot

**Comment by faithiology** [comment]
> Please try to reproduce the problem in OCA runbot

What does this mean :) please explain to us how to report a problem by OCA runbot!

**Comment by TelmoSuarezConinpe** [comment]
I reproduced the problem in runbot following the next steps:
- Create root folder, set folder name, group with permissions, set root folder to true and storage to "Documents Storage"
- At this point you cannot add files on the form view of the root folder(This raises error)
- Add subfolders
- Save changes
- Try to create new subfolders(This raises error)
- If you have more than 1 subfolders it wont let you delete them in the root folder form
It is important that all of this is made in the form view, in kanban view everything works as expected.

**Comment by victoralmau** [comment]
Hi, it's solved on 14.0 (https://github.com/OCA/dms/pull/158)
