### ISSUE TITLE
Error installing the module

### ISSUE THREAD

**Issue by man4tech** [OCA/dms#162]
module: dms_field
version: 13.0

**Steps to reproduce**
Try to install the module

**Current behavior**
Raise anError 
2022-02-23 14:48:38,917 964 ERROR REVSA_DEV odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo13/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo13/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo13/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo13/odoo/modules/loading.py", line 201, in load_module_graph
    registry.setup_models(cr)
  File "/opt/odoo13/odoo/modules/registry.py", line 255, in setup_models
    model._setup_fields()
  File "/opt/odoo13/odoo/models.py", line 2720, in _setup_fields
    field.setup_full(self)
  File "/opt/odoo13/odoo/fields.py", line 431, in setup_full
    self._setup_regular_full(model)
  File "/opt/odoo13/odoo/fields.py", line 2922, in _setup_regular_full
    invf = comodel._fields[self.inverse_name]
KeyError: 'res_id'
2022-02-23 14:48:38,917 964 ERROR REVSA_DEV odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/opt/odoo13/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo13/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo13/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo13/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-60>", line 2, in button_immediate_install
  File "/opt/odoo13/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo13/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo13/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo13/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo13/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo13/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo13/odoo/modules/loading.py", line 201, in load_module_graph
    registry.setup_models(cr)
  File "/opt/odoo13/odoo/modules/registry.py", line 255, in setup_models
    model._setup_fields()
  File "/opt/odoo13/odoo/models.py", line 2720, in _setup_fields
    field.setup_full(self)
  File "/opt/odoo13/odoo/fields.py", line 431, in setup_full
    self._setup_regular_full(model)
  File "/opt/odoo13/odoo/fields.py", line 2922, in _setup_regular_full
    invf = comodel._fields[self.inverse_name]
KeyError: 'res_id'

**Expected behavior**
Module installs without errors

**Comment by pedrobaeza** [comment]
Are you importing the module instead of putting it in the addons path?

**Comment by man4tech** [comment]
Hi, no i have a custom path for addons "/opt/odoo13/cus" and i put the module folder dms_field on there
dms module installed without errors

**Comment by man4tech** [comment]
Reviewing the code of dms_field/models/base.py there is a One2many field toward dms.directory with a inverse name of res_id, but this field doesn't have its counterpart Many2one on dms.directory. Could this be the cause?

**Comment by pedrobaeza** [comment]
@etobella can you clarify?

**Comment by man4tech** [comment]
Update:
I was using the oca zip for installation, remove modules and installed from sources and there was no errors
Testing it
