### ISSUE TITLE
Upload button fails with "file with the same name already exists"

### ISSUE THREAD

**Issue by lorenzomorandini** [OCA/dms#290]
Can not directly upload a new file (using the upload button), the only way is to manually crate a new file (using the create button).

## Module
DMS 16.0.1.1.1

## Describe the bug
Can not directly upload a new file (using the upload button), the only way is to manually crate a new file (using the create button).

## To Reproduce
**Affected versions**:

1. Install the module
2. Configure a database storage (did not try with the other types yet)
3. Try to use the upload button

**Expected behavior**
The file should be uploaded in the currect directory.

**Additional context**
```
2024-02-05 13:25:25,509 1446208 INFO dev werkzeug: 10.30.9.81 - - [05/Feb/2024 13:25:25] "POST /web/binary/upload_attachment HTTP/1.0" 200 - 4 0.006 0.061
2024-02-05 13:25:25,561 1446210 INFO dev werkzeug: 10.30.9.81 - - [05/Feb/2024 13:25:25] "POST /web/dataset/call_kw/dms.file/get_dms_files_from_attachments HTTP/1.0" 200 - 5 0.009 0.026
2024-02-05 13:25:25,618 1446200 ERROR dev odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2003, in __call__
2024-02-05 13:30:24,991 1446217 INFO ? odoo.sql_db: ConnectionPool(used=1/count=1/max=64): Closed 1 connections to 'application_name=odoo-1446217 user=odoo sslmode=prefer dbname=dev' 
2024-02-05 13:30:25,120 1446210 ERROR dev odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2003, in __call__
    response = request._serve_db()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1589, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1616, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1820, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 464, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 444, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-201>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/var/lib/odoo/.local/share/Odoo/addons/16.0/dms/models/dms_file.py", line 583, in create
    vals = self._create_model_attachment(vals)
  File "/var/lib/odoo/.local/share/Odoo/addons/16.0/dms/models/dms_file.py", line 542, in _create_model_attachment
    directory = self.env["dms.directory"].browse(directory_id)
UnboundLocalError: local variable 'directory_id' referenced before assignment
```

**Comment by lorenzomorandini** [comment]
Fixed in #296
