### ISSUE TITLE
[13.0] Exception while changing name or file content

### ISSUE THREAD

**Issue by LorisBalsamo** [OCA/dms#62]
When I try to change the name or the file content of a file in DMS, it shows this exception:

The problem exist in runbot, not only on my local instance.

`Odoo Server Error
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1327, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1319, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/models.py", line 6255, in onchange
    for name in nametree
  File "/.repo_requirements/odoo/odoo/models.py", line 6256, in <listcomp>
    if name not in done and snapshot0.has_changed(name)
  File "/.repo_requirements/odoo/odoo/models.py", line 6101, in has_changed
    return self[name] != record[name]
  File "/.repo_requirements/odoo/odoo/models.py", line 5731, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/.repo_requirements/odoo/odoo/fields.py", line 1032, in __get__
    self.compute_value(recs)
  File "/.repo_requirements/odoo/odoo/fields.py", line 1146, in compute_value
    records._compute_field_value(self)
  File "/.repo_requirements/odoo/odoo/models.py", line 4003, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/odoo/build/OCA/dms/dms/models/dms_file.py", line 414, in _compute_mimetype
    binary = base64.b64decode(record.with_context({}).content or "")
  File "/usr/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding`

**Comment by victoralmau** [comment]
It's solved now in 13.0.
