### ISSUE TITLE
DMS with Odoo 14. Community version install error

### ISSUE THREAD

**Issue by frankofno** [OCA/dms#76]
I just tried to install DMS on the odoo community version 14. 
I manually install web_drop_target and mail_preview_base as asked to do so, before installing dms. DMS appears in the menu list as installed, as soon as I click on it i get an error message saying:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1377, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1369, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 392, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 365, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/addons/dms/models/dms_file.py", line 286, in search_panel_select_range
    field_name, **kwargs
  File "/opt/odoo/odoo/addons/web/models/models.py", line 523, in search_panel_select_range
    set_limit= limit and not (expand or hierarchize or comodel_domain), **kwargs
  File "/opt/odoo/odoo/addons/web/models/models.py", line 265, in _search_panel_field_image
    set_limit and limit,
  File "/opt/odoo/odoo/addons/web/models/models.py", line 307, in _search_panel_domain_image
    groups = self.read_group(domain, [field_name], [field_name], limit=limit)
  File "/opt/odoo/odoo/odoo/models.py", line 2250, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/opt/odoo/odoo/odoo/models.py", line 2278, in _read_group_raw
    annotated_groupbys = [self._read_group_process_groupby(gb, query) for gb in groupby_list]
  File "/opt/odoo/odoo/odoo/models.py", line 2278, in <listcomp>
    annotated_groupbys = [self._read_group_process_groupby(gb, query) for gb in groupby_list]
  File "/opt/odoo/odoo/addons/dms/models/dms_file.py", line 471, in _read_group_process_groupby
    self.env["dms.directory"].with_context(prefetch_fields=False).search([])
  File "/opt/odoo/odoo/odoo/models.py", line 1704, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo/odoo/addons/dms/models/directory.py", line 346, in _search
    args, offset, limit, order, False, access_rights_uid
  File "/opt/odoo/odoo/odoo/models.py", line 4493, in _search
    self._apply_ir_rules(query, 'read')
  File "/opt/odoo/odoo/addons/dms/models/dms_security_mixin.py", line 142, in _apply_ir_rules
    self._apply_access_groups(query, mode=mode)
  File "/opt/odoo/odoo/addons/dms/models/dms_security_mixin.py", line 136, in _apply_access_groups
    query.where_clause += [where_clause]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: can only concatenate tuple (not "list") to tuple

**Comment by pedrobaeza** [comment]
The module is not yet migrated. Check #66.
